Base
IndraGunawan/gosample pull request #1
Opened 2018-08-02 10:33 UTC by IndraGunawan

ini sample project dengan golang

note: belum selesai semua, karena belum dibuat test
ping @indrasaputra

2018-08-03 09:29 UTC, indrasaputra requested changes

2018-08-03 09:29 UTC, indrasaputra commented on database/mysql.go
> +	_ "github.com/go-sql-driver/mysql"
ini bisa pake punya Bukalapak.
https://github.com/bukalapak/go-mysql-driver/

2018-08-03 09:29 UTC, indrasaputra commented on database/user.go
> +	select {
block ini nanti dipisah aja. jadi decorator.

block yg semacam ini juga nanti ditiadakan dulu aja. implementasinya biar ga ngerusak proses bisnis utama.

2018-08-03 09:29 UTC, indrasaputra commented on env
> +MYSQL_HOST=127.0.0.1
kayaknya ini gak perlu dicommit. cukup env.sample nya aja.

2018-08-03 09:29 UTC, indrasaputra commented on mock/user.go
> +	users := []gosample.User{
yg kayak gini, mending dimasukkan ke folder testdata.
tapi kalau masih sedikit gini, ditaruh sini juga gak apa2.

2018-08-03 09:29 UTC, indrasaputra commented on user.go
> +type UserService struct {
UserService ini buat apa ya?
kayaknya fungsinya sama persis sama UserRepository

2018-08-03 11:20 UTC, IndraGunawan commented on env
> +MYSQL_HOST=127.0.0.1
ahh iya, sebelum nya file nya `.env` tapi di rename jadi `env` supaya sesuai standar, lupa ganti .gitignore nya.

2018-08-03 11:21 UTC, IndraGunawan commented on database/mysql.go
> +	_ "github.com/go-sql-driver/mysql"
ok, akan diganti

2018-08-03 11:24 UTC, IndraGunawan commented on user.go
> +type UserService struct {
`UserService` sih tujuan nya untuk handle sesuatu saat action dipanggil tetapi tidak berhubungan dengan database, tapi dengan project ini tidak ada kegunaan karena scope nya masih kecil.
akan ditiadakan `UserService` nya

2018-08-06 07:56 UTC, indrasaputra commented on user.go
> +type UserService struct {
I see. okay. goalnya udah oke sih imo.

2018-08-06 07:56 UTC, indrasaputra commented
@IndraGunawan jangan lupa unit test nya difix juga ya

2018-09-17 10:04 UTC, merged